// items.js
const items = [
    {
        id: 1,
        title: "Classic White Dress",
        price: 50.00,
        image: "https://i.imgur.com/nJntMWB.jpeg",
        color: "white",
        size: "S",
        category: "clothing",
    },
    {
        id: 2,
        title: "Director outfit",
        price: 75.00,
        image: "https://i.imgur.com/Po7jHay.jpg",
        color: "blue",
        size: "M",
        category: "clothing",
    },
    {
        id: 3,
        title: "Green Shoes",
        price: 20.00,
        image: "https://source.unsplash.com/random?Green+Shoes",
        color: "green",
        size: "L",
        category: "shoes",
    },
    {
        id: 4,
        title: "Blue Necklace",
        price: 20.00,
        image: "https://source.unsplash.com/random?Blue+Necklace",
        color: "blue",
        size: "S",
        category: "accessories",
    },
    {
        id: 5,
        title: "Gold Bracelet",
        price: 10.00,
        image: "https://source.unsplash.com/random?Gold+Bracelet",
        color: "yellow",
        size: "M",
        category: "accessories",
    },
    {
        id: 6,
        title: "White Handbag",
        price: 35.00,
        image: "https://source.unsplash.com/random?White+Handbag",
        color: "white",
        size: "S",
        category: "accessories",
    },
    {
        id: 7,
        title: "Pink Running Shoes",
        price: 90.00,
        image: "https://source.unsplash.com/random?Pink+Running+Shoes",
        color: "pink",
        size: "L",
        category: "shoes",
    },
    {
        id: 8,
        title: "Purple Boots",
        price: 60.00,
        image: "https://source.unsplash.com/random?Purple+Boots",
        color: "purple",
        size: "M",
        category: "shoes",
    },
    {
        id: 9,
        title: "Red Casual Shirt",
        price: 30.00,
        image: "https://source.unsplash.com/random?Red+Shirt",
        color: "red",
        size: "M",
        category: "clothing",
    },
    {
        id: 10,
        title: "Formal Pants",
        price: 50.00,
        image: "https://source.unsplash.com/random?Formal+Pants",
        color: "black",
        size: "L",
        category: "clothing",
    },
    {
        id: 11,
        title: "Leather Shoes",
        price: 75.00,
        image: "https://source.unsplash.com/random?Leather+Shoes",
        color: "brown",
        size: "L",
        category: "shoes",
    },
    {
        id: 12,
        title: "Silver Earrings",
        price: 20.00,
        image: "https://source.unsplash.com/random?Silver+Earrings",
        color: "silver",
        size: "One Size",
        category: "accessories",
    },
    {
        id: 13,
        title: "Sports Shoes",
        price: 60.00,
        image: "https://source.unsplash.com/random?Sports+Shoes",
        color: "white",
        size: "M",
        category: "shoes",
    },
    {
        id: 14,
        title: "Leather Wallet",
        price: 35.00,
        image: "https://source.unsplash.com/random?Leather+Wallet",
        color: "black",
        size: "One Size",
        category: "accessories",
    },
    {
        id: 15,
        title: "Leather Jacket",
        price: 100.00,
        image: "https://source.unsplash.com/random?Leather+Jacket",
        color: "brown",
        size: "L",
        category: "clothing",
    },
    {
        id: 16,
        title: "Winter Coat",
        price: 120.00,
        image: "https://source.unsplash.com/random?Winter+Coat",
        color: "blue",
        size: "M",
        category: "clothing",
    },
    {
        id: 17,
        title: "Sports Jacket",
        price: 80.00,
        image: "https://source.unsplash.com/random?Sports+Jacket",
        color: "gray",
        size: "M",
        category: "clothing",
    },
    {
        id: 18,
        title: "Leather Belt",
        price: 25.00,
        image: "https://source.unsplash.com/random?Leather+Belt",
        color: "brown",
        size: "M",
        category: "accessories",
    },
    {
        id: 19,
        title: "Sneakers",
        price: 50.00,
        image: "https://source.unsplash.com/random?Sneakers",
        color: "white",
        size: "L",
        category: "shoes",
    },
    {
        id: 20,
        title: "Boots",
        price: 90.00,
        image: "https://source.unsplash.com/random?Boots",
        color: "black",
        size: "M",
        category: "shoes",
    },
];

export default items;
