// items.js
const items = [
    {
        id: 1,
        title: "Item 1",
        price: 50.00,
        image: "https://i.imgur.com/nJntMWB.jpeg",
        color: "white",
        size: "S",
        category: "clothing",
    },
    {
        id: 2,
        title: "Item 2",
        price: 75.00,
        image: "https://i.imgur.com/Po7jHay.jpg",
        color: "blue",
        size: "M",
        category: "clothing",
    },
    {
        id: 3,
        title: "Item 3",
        price: 20.00,
        image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d5f84f54-480d-4186-a0ea-3fea15f59d67/air-force-1-high-se-womens-shoes-X6v8pV.png",
        color: "green",
        size: "L",
        category: "shoes",
    },
    {
        id: 4,
        title: "Item 4",
        price: 20.00,
        image: "https://www.a-fashion-story.com/images/Earring/P128809j.jpg",
        color: "blue",
        size: "S",
        category: "accessories",
    },
    {
        id: 5,
        title: "Item 5",
        price: 10.00,
        image: "https://via.placeholder.com/150",
        color: "yellow",
        size: "M",
        category: "accessories",
    },
    {
        id: 6,
        title: "Item 6",
        price: 35.00,
        image: "https://via.placeholder.com/150",
        color: "white",
        size: "S",
        category: "accessories",
    },
    {
        id: 7,
        title: "Item 7",
        price: 90.00,
        image: "https://via.placeholder.com/150",
        color: "pink",
        size: "L",
        category: "shoes",
    },
    {
        id: 8,
        title: "Item 8",
        price: 60.00,
        image: "https://via.placeholder.com/150",
        color: "purple",
        size: "M",
        category: "shoes",
    },
];

export default items;
